### ISSUE TITLE
This would be one of last "frameworks" I would like to use

### ISSUE THREAD

**Issue by DanielGarcia2060** [ctr-lang/ctr#11]
- You are basically using the same css syntax and adding a lot of clutter to it.
 - There is no solution proposed to most of the real world problems on css, just a "new" way to type css
- I don't see the value of paying for it

Can you please explain **Why is this a good idea?** and **What is the purpose** of this thing?

**Comment by chhuang** [comment]
Please explains what is this? How is this different from Bootstrap? Sparing the keystrokes is not helping people to understand the idea behind this great work.

**Comment by fetchTe** [comment]
@DanielGarcia2060 I've moved away from the token subscription model - it was more or less wishful thinking. Nonetheless, ctr is a CSS framework with built in object oriented functionality to allow for a rich hierarchy of inherited CSS components so that it's not require to list each class in your HTML every single time. This functionality is encompassed through the [class](https://docs.ctr-lang.com/class/general/) feature of ctr. However, in order to accomplish true object oriented functionality there has to be a supporting framework and that is what ctr provides. To better understand why this is advantageous you have to understand the basic premise of [OOCSS](https://www.smashingmagazine.com/2011/12/an-introduction-to-object-oriented-css-oocss/) as well as supporting concepts like [extend](https://philipwalton.com/articles/the-future-of-oocss-a-proposal/).

**Comment by fetchTe** [comment]
Yeah, @chhuang sorry, I now realize I did a pretty shitty job the first time around trying to explain ctr in a succinct manner. But I rewrote the README description and would love to hear if it helps you better understand the idea.
